import type { Tool } from '@/types'

export const TOOLS: Tool[] = [
  // ── Existing 10 tools ────────────────────────────────────────────────────────
  {
    id: 'dns-lookup',
    name: 'DNS Lookup',
    slug: '/tools/dns-lookup',
    category: 'DNS & Networking',
    description: 'Look up DNS records for any domain.',
    longDescription: 'Query DNS records including A, AAAA, MX, TXT, CNAME, NS, and SOA record types for any domain.',
    keywords: ['dns', 'lookup', 'a record', 'aaaa', 'nameserver', 'domain', 'query', 'record', 'network'],
    icon: 'Globe',
    seoTitle: 'Free DNS Lookup Tool - Check DNS Records Online',
    seoDescription: 'Look up A, AAAA, MX, TXT, CNAME and NS DNS records for any domain. Fast, free DNS record checker.',
    relatedTools: ['mx-lookup', 'txt-lookup', 'cname-lookup', 'spf-checker'],
    isPopular: true,
  },
  {
    id: 'mx-lookup',
    name: 'MX Lookup',
    slug: '/tools/mx-lookup',
    category: 'DNS & Networking',
    description: 'Check the mail exchange servers configured for a domain.',
    longDescription: 'Look up MX (Mail Exchange) records to find the mail servers responsible for accepting email for a domain.',
    keywords: ['mx', 'mail', 'exchange', 'email', 'server', 'smtp', 'dns', 'record'],
    icon: 'Mail',
    seoTitle: 'Free MX Lookup Tool - Check Mail Exchange Records',
    seoDescription: 'Check MX records to find mail servers for any domain. Verify email delivery configuration.',
    relatedTools: ['dns-lookup', 'spf-checker', 'dkim-checker', 'dmarc-checker'],
    isPopular: true,
  },
  {
    id: 'txt-lookup',
    name: 'TXT Record Lookup',
    slug: '/tools/txt-lookup',
    category: 'DNS & Networking',
    description: 'Find TXT records configured for a domain.',
    longDescription: 'Query TXT DNS records for any domain. Used for domain verification, SPF, DKIM, DMARC.',
    keywords: ['txt', 'text', 'record', 'dns', 'spf', 'dkim', 'dmarc', 'domain', 'verification'],
    icon: 'FileText',
    seoTitle: 'Free TXT Record Lookup Tool - Check DNS TXT Records',
    seoDescription: 'Look up TXT DNS records for any domain. Find SPF, DKIM, DMARC and domain verification records.',
    relatedTools: ['dns-lookup', 'spf-checker', 'dkim-checker', 'dmarc-checker'],
    isPopular: false,
  },
  {
    id: 'cname-lookup',
    name: 'CNAME Lookup',
    slug: '/tools/cname-lookup',
    category: 'DNS & Networking',
    description: 'Check the canonical name configured for a domain or hostname.',
    longDescription: 'Look up CNAME (Canonical Name) records to find where a hostname or subdomain is pointing.',
    keywords: ['cname', 'canonical', 'alias', 'dns', 'domain', 'subdomain', 'redirect', 'record'],
    icon: 'ArrowRight',
    seoTitle: 'Free CNAME Lookup Tool - Check CNAME Records Online',
    seoDescription: 'Look up CNAME records to find canonical name aliases for any hostname.',
    relatedTools: ['dns-lookup', 'txt-lookup', 'mx-lookup'],
    isPopular: false,
  },
  {
    id: 'spf-checker',
    name: 'SPF Checker',
    slug: '/tools/spf-checker',
    category: 'Email & Deliverability',
    description: 'Check whether a domain has a valid SPF record.',
    longDescription: 'Validate your domain\'s SPF (Sender Policy Framework) record.',
    keywords: ['spf', 'sender policy framework', 'email', 'authentication', 'spam', 'deliverability', 'mail'],
    icon: 'ShieldCheck',
    seoTitle: 'Free SPF Record Checker - Validate SPF Configuration',
    seoDescription: 'Check and validate SPF records for your domain. Ensure proper email authentication.',
    relatedTools: ['dkim-checker', 'dmarc-checker', 'mx-lookup', 'txt-lookup'],
    isPopular: true,
  },
  {
    id: 'dkim-checker',
    name: 'DKIM Checker',
    slug: '/tools/dkim-checker',
    category: 'Email & Deliverability',
    description: 'Check DKIM configuration for your email domain.',
    longDescription: 'Verify DKIM (DomainKeys Identified Mail) configuration for your domain.',
    keywords: ['dkim', 'domainkeys', 'email', 'authentication', 'signature', 'public key', 'selector'],
    icon: 'Key',
    seoTitle: 'Free DKIM Checker - Verify DKIM Email Authentication',
    seoDescription: 'Check DKIM configuration for any domain and selector.',
    relatedTools: ['spf-checker', 'dmarc-checker', 'mx-lookup', 'txt-lookup'],
    isPopular: true,
  },
  {
    id: 'dmarc-checker',
    name: 'DMARC Checker',
    slug: '/tools/dmarc-checker',
    category: 'Email & Deliverability',
    description: 'Check and analyze your domain\'s DMARC policy.',
    longDescription: 'Analyze your domain\'s DMARC policy. DMARC builds on SPF and DKIM to give domain owners control.',
    keywords: ['dmarc', 'domain authentication', 'email', 'policy', 'quarantine', 'reject', 'reporting'],
    icon: 'ShieldAlert',
    seoTitle: 'Free DMARC Checker - Analyze DMARC Policy Configuration',
    seoDescription: 'Check and analyze DMARC policies for any domain.',
    relatedTools: ['spf-checker', 'dkim-checker', 'mx-lookup', 'txt-lookup'],
    isPopular: true,
  },
  {
    id: 'ssl-checker',
    name: 'SSL Checker',
    slug: '/tools/ssl-checker',
    category: 'SSL & Security',
    description: 'Check SSL certificate information for a website.',
    longDescription: 'Inspect SSL/TLS certificate details for any domain. Verify certificate validity and expiry dates.',
    keywords: ['ssl', 'tls', 'certificate', 'https', 'security', 'expiry', 'cert'],
    icon: 'Lock',
    seoTitle: 'Free SSL Certificate Checker - Verify SSL/TLS Configuration',
    seoDescription: 'Check SSL certificate validity, expiry dates, and TLS configuration for any domain.',
    relatedTools: ['dns-lookup', 'dmarc-checker', 'spf-checker'],
    isPopular: true,
  },
  {
    id: 'cidr-calculator',
    name: 'CIDR Calculator',
    slug: '/tools/cidr-calculator',
    category: 'DNS & Networking',
    description: 'Calculate network ranges, subnet masks and usable hosts from CIDR notation.',
    longDescription: 'Calculate subnet details from CIDR notation. Get network address, broadcast address, subnet mask.',
    keywords: ['cidr', 'subnet', 'network', 'ip', 'mask', 'calculator', 'broadcast', 'usable hosts', 'networking'],
    icon: 'Network',
    seoTitle: 'Free CIDR Calculator - Subnet Mask & Network Range Calculator',
    seoDescription: 'Calculate subnet details from CIDR notation. Find network address, broadcast, subnet mask, usable hosts.',
    relatedTools: ['subnet-calculator', 'ipv4-calculator', 'ip-range-calculator'],
    isPopular: true,
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    slug: '/tools/json-formatter',
    category: 'Developer Utilities',
    description: 'Format, validate and minify JSON data.',
    longDescription: 'Format and validate JSON with syntax highlighting, minify for production, detect errors.',
    keywords: ['json', 'formatter', 'validator', 'minify', 'pretty print', 'format', 'developer', 'utility'],
    icon: 'Braces',
    seoTitle: 'Free JSON Formatter & Validator - Format and Validate JSON Online',
    seoDescription: 'Format, validate and minify JSON data online. Instant JSON formatting with error detection.',
    relatedTools: ['json-validator', 'json-minifier', 'json-yaml', 'json-csv'],
    isPopular: true,
  },

  // ── New 20 tools ─────────────────────────────────────────────────────────────

  // Networking
  {
    id: 'subnet-calculator',
    name: 'Subnet Calculator',
    slug: '/tools/subnet-calculator',
    category: 'Networking',
    description: 'Calculate IPv4 subnet details including network address, broadcast, and usable hosts.',
    longDescription: 'Full IPv4 subnet calculator. Enter any CIDR block and instantly get network address, broadcast address, subnet mask, wildcard mask, first/last usable IPs, total addresses and binary representation.',
    keywords: ['subnet', 'calculator', 'ipv4', 'cidr', 'network', 'mask', 'broadcast', 'usable hosts', 'subnetting'],
    icon: 'Network',
    seoTitle: 'Subnet Calculator - Free IPv4 CIDR Calculator',
    seoDescription: 'Calculate IPv4 subnet masks, network addresses, broadcast addresses, usable hosts and IP ranges. Free online subnet calculator.',
    relatedTools: ['cidr-calculator', 'ipv4-calculator', 'ip-range-calculator'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'ipv4-calculator',
    name: 'IPv4 Calculator',
    slug: '/tools/ipv4-calculator',
    category: 'Networking',
    description: 'Calculate IPv4 address details including class, private/public classification and binary representation.',
    longDescription: 'Dedicated IPv4 calculator with address class detection, private/public classification, network boundaries and binary breakdown. Fully client-side.',
    keywords: ['ipv4', 'calculator', 'ip address', 'network', 'class', 'private', 'public', 'binary', 'subnet'],
    icon: 'Cpu',
    seoTitle: 'IPv4 Calculator - Free IP Address Calculator',
    seoDescription: 'Calculate IPv4 address class, network address, broadcast address, subnet mask and binary representation online.',
    relatedTools: ['subnet-calculator', 'ip-range-calculator', 'cidr-calculator'],
    isNew: true,
  },
  {
    id: 'ipv6-calculator',
    name: 'IPv6 Calculator',
    slug: '/tools/ipv6-calculator',
    category: 'Networking',
    description: 'Expand, compress and analyse IPv6 addresses with prefix and address type detection.',
    longDescription: 'Full IPv6 calculator supporting compressed and expanded notation. Detects address type (global unicast, link-local, unique local, multicast, loopback, unspecified).',
    keywords: ['ipv6', 'calculator', 'ip address', 'compressed', 'expanded', 'prefix', 'link-local', 'global unicast'],
    icon: 'Globe2',
    seoTitle: 'IPv6 Calculator - Free IPv6 Address & CIDR Calculator',
    seoDescription: 'Expand, compress and analyse IPv6 addresses. Detect address type and network prefix online for free.',
    relatedTools: ['ipv4-calculator', 'subnet-calculator'],
    isNew: true,
  },
  {
    id: 'ip-range-calculator',
    name: 'IP Range Calculator',
    slug: '/tools/ip-range-calculator',
    category: 'Networking',
    description: 'Calculate the range between two IPv4 addresses or from a CIDR block.',
    longDescription: 'Enter a start and end IP address to calculate total IPs, first/last address, range size and CIDR approximation. Also accepts CIDR notation. All calculations are client-side.',
    keywords: ['ip range', 'calculator', 'ipv4', 'start ip', 'end ip', 'cidr', 'network range', 'address range'],
    icon: 'ArrowLeftRight',
    seoTitle: 'IP Range Calculator - Calculate IPv4 Address Ranges',
    seoDescription: 'Calculate IPv4 address ranges between start and end IPs. Find total addresses, CIDR approximation and more.',
    relatedTools: ['subnet-calculator', 'ipv4-calculator', 'cidr-calculator'],
    isNew: true,
  },

  // Data & Developer
  {
    id: 'json-validator',
    name: 'JSON Validator',
    slug: '/tools/json-validator',
    category: 'Data & Developer',
    description: 'Validate JSON syntax with precise error location reporting.',
    longDescription: 'Validate JSON input, report syntax errors with line and column numbers, and pretty-print valid JSON. All processing happens entirely in the browser.',
    keywords: ['json', 'validator', 'validate', 'syntax', 'error', 'pretty print', 'format', 'lint'],
    icon: 'CheckSquare',
    seoTitle: 'JSON Validator - Validate JSON Online',
    seoDescription: 'Validate JSON syntax online. Get precise error messages with line and column numbers. Free JSON validator.',
    relatedTools: ['json-formatter', 'json-minifier', 'json-yaml', 'json-csv'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    slug: '/tools/json-minifier',
    category: 'Data & Developer',
    description: 'Minify JSON by removing whitespace to reduce file size.',
    longDescription: 'Remove all unnecessary whitespace from JSON to produce compact output. Shows original size, minified size and percentage reduction. Works entirely in the browser.',
    keywords: ['json', 'minifier', 'minify', 'compress', 'compact', 'size', 'optimize', 'whitespace'],
    icon: 'Minimize2',
    seoTitle: 'JSON Minifier - Compress JSON Online',
    seoDescription: 'Minify and compress JSON by removing whitespace. See exact size reduction. Free online JSON minifier.',
    relatedTools: ['json-formatter', 'json-validator'],
    isNew: true,
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML Converter',
    slug: '/tools/json-yaml',
    category: 'Data & Developer',
    description: 'Convert between JSON and YAML formats in both directions.',
    longDescription: 'Two-way converter between JSON and YAML. Convert JSON to YAML or YAML to JSON with validation and error reporting. Runs entirely in the browser.',
    keywords: ['json', 'yaml', 'converter', 'convert', 'transform', 'data format', 'serialization'],
    icon: 'ArrowLeftRight',
    seoTitle: 'JSON to YAML Converter - Convert JSON and YAML Online',
    seoDescription: 'Convert JSON to YAML or YAML to JSON online. Free two-way JSON/YAML converter with validation.',
    relatedTools: ['json-validator', 'yaml-validator', 'json-formatter'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'json-csv',
    name: 'JSON ↔ CSV Converter',
    slug: '/tools/json-csv',
    category: 'Data & Developer',
    description: 'Convert JSON arrays to CSV and CSV data back to JSON.',
    longDescription: 'Convert JSON arrays to CSV with proper quoting and escaping, or parse CSV (including quoted fields with commas) into JSON. All processing is client-side.',
    keywords: ['json', 'csv', 'converter', 'convert', 'spreadsheet', 'table', 'data', 'import', 'export'],
    icon: 'Table',
    seoTitle: 'JSON to CSV Converter - Convert JSON Data to CSV',
    seoDescription: 'Convert JSON arrays to CSV or CSV to JSON online. Handles quoted fields and special characters. Free.',
    relatedTools: ['json-validator', 'json-formatter'],
    isNew: true,
  },
  {
    id: 'yaml-validator',
    name: 'YAML Validator',
    slug: '/tools/yaml-validator',
    category: 'Data & Developer',
    description: 'Validate YAML syntax and preview the parsed structure.',
    longDescription: 'Validate YAML files, show syntax errors with line numbers, and preview the parsed result as JSON. Supports all common YAML structures. Runs in the browser.',
    keywords: ['yaml', 'validator', 'validate', 'syntax', 'error', 'lint', 'kubernetes', 'docker', 'config'],
    icon: 'FileCode',
    seoTitle: 'YAML Validator - Validate YAML Online',
    seoDescription: 'Validate YAML syntax online with line-number error reporting. Preview parsed structure as JSON.',
    relatedTools: ['json-yaml', 'kubernetes-generator', 'docker-compose-generator'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    slug: '/tools/xml-formatter',
    category: 'Data & Developer',
    description: 'Format, minify and validate XML documents.',
    longDescription: 'Pretty-print or minify XML with configurable indentation. Detects malformed XML and reports the error. All processing runs in the browser using the browser\'s native XML parser.',
    keywords: ['xml', 'formatter', 'format', 'minify', 'validate', 'pretty print', 'beautify', 'markup'],
    icon: 'Code',
    seoTitle: 'XML Formatter - Format and Beautify XML Online',
    seoDescription: 'Format, minify and validate XML documents online. Configurable indentation and error reporting.',
    relatedTools: ['json-formatter', 'yaml-validator'],
    isNew: true,
  },

  // Security & Developer
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    slug: '/tools/jwt-decoder',
    category: 'Security & Developer',
    description: 'Decode and inspect JSON Web Tokens — completely client-side.',
    longDescription: 'Decode JWT header, payload and signature. Inspect standard claims (iss, sub, exp, iat, nbf). Calculate expiry status. Your token never leaves the browser.',
    keywords: ['jwt', 'json web token', 'decode', 'token', 'bearer', 'claims', 'auth', 'authentication', 'exp', 'iat'],
    icon: 'KeyRound',
    seoTitle: 'JWT Decoder - Decode JSON Web Tokens Online',
    seoDescription: 'Decode JWT tokens and inspect header, payload and claims online. 100% client-side — your token is never sent to a server.',
    relatedTools: ['json-formatter', 'base64', 'hash-generator'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    slug: '/tools/hash-generator',
    category: 'Security & Developer',
    description: 'Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes using the Web Crypto API.',
    longDescription: 'Generate cryptographic hashes using the browser\'s native Web Crypto API. Supports SHA-1, SHA-256, SHA-384 and SHA-512. Optional file hashing. Nothing is uploaded or sent to a server.',
    keywords: ['hash', 'sha256', 'sha512', 'sha384', 'sha1', 'crypto', 'checksum', 'digest', 'web crypto'],
    icon: 'Hash',
    seoTitle: 'Hash Generator - SHA-256, SHA-512 Hash Generator',
    seoDescription: 'Generate SHA-256, SHA-512 and other cryptographic hashes online. Uses browser Web Crypto API — no server upload.',
    relatedTools: ['base64', 'jwt-decoder', 'url-encoder'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'base64',
    name: 'Base64 Encoder / Decoder',
    slug: '/tools/base64',
    category: 'Security & Developer',
    description: 'Encode and decode Base64 with full Unicode support.',
    longDescription: 'Encode text or files to Base64 and decode Base64 strings back to text. Full Unicode/emoji/multilingual support using proper UTF-8 handling. Entirely client-side.',
    keywords: ['base64', 'encode', 'decode', 'encoding', 'unicode', 'utf8', 'binary', 'text', 'converter'],
    icon: 'Binary',
    seoTitle: 'Base64 Encoder & Decoder - Encode and Decode Base64',
    seoDescription: 'Encode and decode Base64 online with full Unicode support. Encode files to Base64. 100% client-side.',
    relatedTools: ['jwt-decoder', 'url-encoder', 'hash-generator'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder / Decoder',
    slug: '/tools/url-encoder',
    category: 'Security & Developer',
    description: 'Encode and decode URL components and full URLs.',
    longDescription: 'Encode and decode URL components using encodeURIComponent/decodeURIComponent and full URL encoding. Handles special characters, Unicode and malformed percent-encoding gracefully.',
    keywords: ['url', 'encode', 'decode', 'encoding', 'percent', 'uri', 'component', 'query string', 'escape'],
    icon: 'Link',
    seoTitle: 'URL Encoder & Decoder - Encode URLs Online',
    seoDescription: 'Encode and decode URL components and full URLs online. Handles Unicode and special characters.',
    relatedTools: ['base64', 'regex-tester'],
    isNew: true,
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    slug: '/tools/regex-tester',
    category: 'Security & Developer',
    description: 'Test regular expressions with live match highlighting and capture groups.',
    longDescription: 'Test JavaScript regular expressions with live highlighting of all matches. View capture groups, match index and length. Select flags (g, i, m, s, u, y). Built-in common regex examples.',
    keywords: ['regex', 'regular expression', 'tester', 'test', 'match', 'pattern', 'flags', 'capture group'],
    icon: 'Regex',
    seoTitle: 'Regex Tester - Test Regular Expressions Online',
    seoDescription: 'Test regular expressions with live match highlighting, capture groups and common examples. Free online regex tester.',
    relatedTools: ['diff-checker', 'json-validator'],
    isNew: true,
    isPopular: true,
  },

  // Developer
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    slug: '/tools/diff-checker',
    category: 'Developer',
    description: 'Compare two text blocks and highlight additions, deletions and changes.',
    longDescription: 'Side-by-side and unified diff view for two text blocks. Shows added, removed and changed lines with statistics. Options to ignore whitespace and case. Entirely client-side.',
    keywords: ['diff', 'compare', 'text', 'difference', 'added', 'removed', 'changed', 'unified', 'side by side'],
    icon: 'GitCompare',
    seoTitle: 'Diff Checker - Compare Text Online',
    seoDescription: 'Compare two text blocks online. See added, removed and changed lines in side-by-side or unified view.',
    relatedTools: ['json-formatter', 'json-validator', 'yaml-validator'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'cron-generator',
    name: 'Cron Generator',
    slug: '/tools/cron-generator',
    category: 'Developer',
    description: 'Build Linux cron expressions with a visual editor and human-readable explanations.',
    longDescription: 'Visual 5-field cron expression generator for Linux/Unix. Select minute, hour, day of month, month and day of week. Get a human-readable explanation and one-click copy.',
    keywords: ['cron', 'crontab', 'schedule', 'linux', 'unix', 'expression', 'generator', 'job', 'task scheduler'],
    icon: 'Clock',
    seoTitle: 'Cron Generator - Create Linux Cron Expressions',
    seoDescription: 'Generate Linux cron expressions with a visual editor. Get human-readable explanations for any cron schedule.',
    relatedTools: ['chmod-calculator', 'kubernetes-generator'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'chmod-calculator',
    name: 'Linux chmod Calculator',
    slug: '/tools/chmod-calculator',
    category: 'Developer',
    description: 'Calculate Linux file permissions with checkboxes and get the chmod command.',
    longDescription: 'Interactive Linux permission calculator. Toggle read/write/execute for owner, group and others. Includes SUID, SGID and sticky bit. Shows numeric, symbolic and chmod command.',
    keywords: ['chmod', 'permissions', 'linux', 'unix', 'rwx', 'owner', 'group', 'suid', 'sgid', 'sticky bit', 'octal'],
    icon: 'Shield',
    seoTitle: 'Chmod Calculator - Linux File Permissions Calculator',
    seoDescription: 'Calculate Linux file permissions online. Get numeric mode, symbolic notation and chmod command.',
    relatedTools: ['cron-generator', 'docker-compose-generator'],
    isNew: true,
    isPopular: true,
  },

  // DevOps
  {
    id: 'docker-compose-generator',
    name: 'Docker Compose Generator',
    slug: '/tools/docker-compose-generator',
    category: 'DevOps',
    description: 'Generate Docker Compose YAML files with a visual form — no Docker required.',
    longDescription: 'Build Docker Compose configurations visually. Add multiple services with image, ports, environment variables, volumes, networks, restart policy and more. Download ready-to-use YAML.',
    keywords: ['docker', 'compose', 'docker-compose', 'yaml', 'generator', 'container', 'service', 'devops'],
    icon: 'Container',
    seoTitle: 'Docker Compose Generator - Create Docker Compose YAML',
    seoDescription: 'Generate Docker Compose YAML files visually. Add services, ports, volumes and environment variables. Download instantly.',
    relatedTools: ['yaml-validator', 'kubernetes-generator', 'chmod-calculator'],
    isNew: true,
    isPopular: true,
  },
  {
    id: 'kubernetes-generator',
    name: 'Kubernetes YAML Generator',
    slug: '/tools/kubernetes-generator',
    category: 'DevOps',
    description: 'Generate Kubernetes YAML manifests for Deployment, Service, Ingress and more.',
    longDescription: 'Visual generator for Kubernetes manifests: Deployment, Service, Ingress, Namespace, ConfigMap, Job and CronJob. Set resource limits, environment variables and labels. Download YAML.',
    keywords: ['kubernetes', 'k8s', 'yaml', 'generator', 'deployment', 'service', 'ingress', 'namespace', 'devops', 'manifest'],
    icon: 'Server',
    seoTitle: 'Kubernetes YAML Generator - Create Kubernetes Manifests',
    seoDescription: 'Generate Kubernetes YAML manifests for Deployment, Service, Ingress and Namespace. Download and use immediately.',
    relatedTools: ['yaml-validator', 'docker-compose-generator', 'cron-generator'],
    isNew: true,
    isPopular: true,
  },
]

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find((t) => t.id === id)
}

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find((t) => t.slug === slug)
}

export function getToolsByCategory(category: string): Tool[] {
  return TOOLS.filter((t) => t.category === category)
}

export function getRelatedTools(toolId: string): Tool[] {
  const tool = getToolById(toolId)
  if (!tool) return []
  return tool.relatedTools
    .map((id) => getToolById(id))
    .filter((t): t is Tool => !!t)
    .slice(0, 4)
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase().trim()
  if (!q) return TOOLS
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.toLowerCase().includes(q))
  )
}

export function getPopularTools(): Tool[] {
  return TOOLS.filter((t) => t.isPopular)
}
